config/routes.rb
Rails.application.routes.draw do
  resources :everydaytips

  resources :odsreserves

  get 'about/help'

  resources :analysts

  resources :syslogs

  resources :portfoliologs

  resources :weixinlogs

  resources :marketdates do
		get 'reset_marketdate_to_today', on: :collection
	end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: "users/sessions" }
  get 'welcome/index'

  resources :sysconfigs

  resources :quotationdatafiles do
		get 'doupdate', on: :member
		get 'bxctoodsupdate', on: :member
		get 'dobatch', on: :collection
	end

  resources :reserves do
    post 'qcode', on: :collection
    get 'pubindex', on: :collection
  end

  resources :quotations

  resources :accounts

  resources :portfolios

  resources :users

  mount WeixinRailsMiddleware::Engine, at: "/"

  get '/pub/index', to: 'reserves#pubindex', as: 'sysanalyst'
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
		if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
	has_attached_file :avatar, 
	:styles => { 
		:medium => {
			:processors =>[:watermark], 
			:geometry => '800x500',
			:watermark_path => "#{Rails.root}/public/1.jpg",
			:percentage => '20%',
			:position => 'Center'
		}
	}, 
	:path => ":rails_root/public/downloads/:id.:extension",
	:url => "/downloads/:id.:extension",
	:default_url => "/downloads/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	has_many	:portfolios
	#has_many	:follows
	#has_many	:analysts, through: :follows
	belongs_to :analyst
	belongs_to	:user
	resourcify
end

app/models/analyst.rb
class Analyst < ActiveRecord::Base
	has_many	:reserve
	#has_many	:follows
	#has_many	:accounts, through: :follows
	has_many	:accounts
  belongs_to :user
end

app/models/everydaytip.rb
class Everydaytip < ActiveRecord::Base
end

app/models/marketdate.rb
class Marketdate < ActiveRecord::Base
end

app/models/odsreserf.rb
class Odsreserf < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	belongs_to	:account
	belongs_to	:quotation
	resourcify
	scope :daydata, ->(marketdate) { where("marketdate = ?", marketdate) }
end

app/models/portfoliolog.rb
class Portfoliolog < ActiveRecord::Base
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	resourcify
	scope :daydata, ->(marketdate) { where("marketdate = ?", marketdate) }
	has_many	:portfolio
	has_many	:reserve
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
	include QuotationdatafilesHelper
	belongs_to	:quotation
	belongs_to	:analyst
	resourcify
	scope	:daydata, ->(marketdate) { where("marketdate = ?", marketdate) }
	
	class << self
		def refresh(close)
			unless close <= 0
         profit = (hhv - close)/close
         loss = (close - llv)/close
         plratio = profit / loss
         optadvise = 'buy' unless plratio < 2
         stockstatus = 1
       end
		end
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sysconfig.rb
class Sysconfig < ActiveRecord::Base
  has_attached_file :imgfile, 
      :styles => { :poster => "1280x1280", :large => "860x860", :medium => "430x430", :small => "344x344", :thumb => "258x258" }

      validates_attachment :imgfile,
      :content_type => { :content_type => /\Aimage\/.*\Z/ } ,
      :size => { :in => 0..1000.kilobytes }


  has_attached_file :txtfile 

      validates_attachment :txtfile,
      :content_type => { :content_type => ["text/plain"] } ,
      :size => { :in => 0..1000.kilobytes }

	resourcify
end

app/models/syslog.rb
class Syslog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable
	has_many	:accounts
  has_one :analyst
end

app/models/weixinlog.rb
class Weixinlog < ActiveRecord::Base
end

app/controllers/marketdates_controller.rb
class MarketdatesController < ApplicationController
  before_action :set_marketdate, only: [:show, :edit, :update, :destroy]

  # GET /marketdates
  # GET /marketdates.json
  def index
    @marketdates = Marketdate.all
  end
	
	def reset_marketdate_to_today
		ActiveRecord::Base.transaction do
			md = Sysconfig.find_by(cfgname: 'marketdate').cfgdate
			Marketdate.where("tradedate < ?", md).update_all(daystate: 'past')
			#Marketdate.where("tradedate < ?", "#{Time.new.strftime("%Y-%m-%d")}").update_all(daystate: 'past')
			Marketdate.where("tradedate >= ?", md).update_all(daystate: '')
			#Marketdate.where("tradedate >= ?", "#{Time.new.strftime("%Y-%m-%d")}").update_all(daystate: '')
			#Sysconfig.find_by(cfgname: 'marketdate').update!(cfgdate: Time.new)
			Sysconfig.find_by(cfgname: 'batchname').update!(cfgstring: 'datechange')
			Sysconfig.find_by(cfgname: 'batchstatus').update!(cfginteger: 0)
		end
		redirect_to reserves_path
	end

  # GET /marketdates/1
  # GET /marketdates/1.json
  def show
  end

  # GET /marketdates/new
  def new
    @marketdate = Marketdate.new
  end

  # GET /marketdates/1/edit
  def edit
  end

  # POST /marketdates
  # POST /marketdates.json
  def create
    @marketdate = Marketdate.new(marketdate_params)

    respond_to do |format|
      if @marketdate.save
        format.html { redirect_to @marketdate, notice: 'Marketdate was successfully created.' }
        format.json { render :show, status: :created, location: @marketdate }
      else
        format.html { render :new }
        format.json { render json: @marketdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marketdates/1
  # PATCH/PUT /marketdates/1.json
  def update
    respond_to do |format|
      if @marketdate.update(marketdate_params)
        format.html { redirect_to @marketdate, notice: 'Marketdate was successfully updated.' }
        format.json { render :show, status: :ok, location: @marketdate }
      else
        format.html { render :edit }
        format.json { render json: @marketdate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marketdates/1
  # DELETE /marketdates/1.json
  def destroy
    @marketdate.destroy
    respond_to do |format|
      format.html { redirect_to marketdates_url, notice: 'Marketdate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marketdate
      @marketdate = Marketdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marketdate_params
      params.require(:marketdate).permit(:tradedate, :daystate)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/analysts_helper.rb
module AnalystsHelper
end

app/helpers/marketdates_helper.rb
module MarketdatesHelper
end

app/helpers/syslogs_helper.rb
module SyslogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/marketdates/_form.html.erb
<%= simple_form_for @marketdate, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :tradedate %>
  <%= error_span(@marketdate[:tradedate]) %>
  <%= f.input :daystate %>
  <%= error_span(@marketdate[:daystate]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                marketdates_path, :class => 'btn btn-default' %>
<% end %>

app/views/marketdates/edit.html.erb
<%- model_class = Marketdate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marketdates/index.html.erb
<%- model_class = Marketdate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:tradedate) %></th>
      <th><%= model_class.human_attribute_name(:daystate) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @marketdates.each do |marketdate| %>
      <tr>
        <td><%= link_to marketdate.id, marketdate_path(marketdate) %></td>
        <td><%= marketdate.tradedate %></td>
        <td><%= marketdate.daystate %></td>
        <td><%=l marketdate.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_marketdate_path(marketdate), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      marketdate_path(marketdate),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_marketdate_path,
            :class => 'btn btn-primary' %>

app/views/marketdates/new.html.erb
<%- model_class = Marketdate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/marketdates/show.html.erb
<%- model_class = Marketdate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:tradedate) %>:</strong></dt>
  <dd><%= @marketdate.tradedate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:daystate) %>:</strong></dt>
  <dd><%= @marketdate.daystate %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              marketdates_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_marketdate_path(@marketdate), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              marketdate_path(@marketdate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>