config/routes.rb
Rails.application.routes.draw do
  resources :everydaytips

  resources :odsreserves

  get 'about/help'

  resources :analysts

  resources :syslogs

  resources :portfoliologs

  resources :weixinlogs

  resources :marketdates do
		get 'reset_marketdate_to_today', on: :collection
	end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: "users/sessions" }
  get 'welcome/index'

  resources :sysconfigs

  resources :quotationdatafiles do
		get 'doupdate', on: :member
		get 'bxctoodsupdate', on: :member
		get 'dobatch', on: :collection
	end

  resources :reserves do
    post 'qcode', on: :collection
    get 'pubindex', on: :collection
  end

  resources :quotations

  resources :accounts

  resources :portfolios

  resources :users

  mount WeixinRailsMiddleware::Engine, at: "/"

  get '/pub/index', to: 'reserves#pubindex', as: 'sysanalyst'
  root 'welcome#index'

end

app/models/quotationdatafile.rb
class Quotationdatafile < ActiveRecord::Base
	has_attached_file :avatar,
  :path => ":rails_root/public/uploads/:class/:basename.:id.:extension",  
  #:path => ":rails_root/public/uploads/:filetype}/:marketdate_:id.:extension",  
  :url => "/uploads/:id.:extension",  
  :default_url => "/uploads/default.txt"

  validates_attachment :avatar, :presence => true,
  :content_type => { :content_type => ["application/vnd.ms-excel", "application/excel", "text/plain"] } ,
  :content_type_mappings => { xls: "text" },
  #:matches => [/xls\Z/],
  :size => { :in => 0..1000.kilobytes }
  #do_not_validate_attachment_file_type :avatar

	resourcify
end

app/helpers/quotationdatafiles_helper.rb
#encoding:utf-8
require 'gruff'

module QuotationdatafilesHelper


#	1. input today quotation
	#	1.1 update profit
# 2. input today reserver
# 3. modify today reserver
# 4. select portfolio by pretradedate data
# 5. date change
# 6. select portfolio by tradedate data
	def sysmarketdate
		return Sysconfig.find_by(cfgname: 'marketdate').cfgdate
	end
	
	def config_get cfgname
		case cfgname
		when 'batchname'
			return Sysconfig.find_by(cfgname: 'batchname').cfgstring	
		when 'batchstatus'
			return Sysconfig.find_by(cfgname: 'batchstatus').cfginteger	
		else

		end
	end
	
	def config_set cfgname, cfgvalue
		case cfgname
		when 'batchname'
			return Sysconfig.find_by(cfgname: 'batchname').update(cfgstring: cfgvalue)
		when 'batchstatus'
			return Sysconfig.find_by(cfgname: 'batchstatus').update(cfginteger: cfgvalue)
		else

		end
	end

	def tradedate
		m = Marketdate.where("daystate = ''").order(tradedate: :asc).first
		return m.tradedate unless m.nil?
	end

	def pretradedate
		m = Marketdate.where("daystate = 'past'").order(tradedate: :asc).last
		return m.tradedate unless m.nil?
	end

	def posttradedate
		m = Marketdate.where("daystate = ''").order(tradedate: :asc).limit(2).last
		return m.tradedate unless m.nil?
	end

	def marketdatechange
		m = Marketdate.where("daystate = ''").order(tradedate: :asc).first
		m.update!(daystate: 'past')
		Sysconfig.find_by(cfgname: 'marketdate').update!(cfgdate: tradedate)
	end
	
	def sysaccount_num_max
		return Sysconfig.find_by(cfgname: 'account_num_max').cfginteger
	end

	def sysportfolio_num_max
		return Sysconfig.find_by(cfgname: 'portfolio_num_max').cfginteger
	end

	
	def marketdatefileprocess path
		File.open(@quotationdatafile.avatar.path, 'r') do |file|
      file.each_line do |line|
        cols = line.force_encoding('gb2312').split("\r\n")
        logger.info cols
        m = Marketdate.new
        m.tradedate = cols[0].strip

        m.save
      end
    end
	end

	# before date 
	# 20140723 all data
	# 20140724 tradedate 
	# after date
	# 20140724 all data
	# 20140725 tradedate
	def quotationfileprocess path 
    File.open(path, 'r') do |file|
      file.each_line do |line|
        cols = line.force_encoding('gb2312').split("\t")
        if /\d{6}/ =~ cols[0][2..7].strip
					#added new quotation
          q = Quotation.new
          q.marketdate = tradedate
 
          q.code = cols[0][2..7].strip
          q.name = cols[1].strip
          q.cqstatus = 'chuquan' unless q.name[0..1] != 'XD'
          q.plate = cols[18].strip

          if cols[11].strip == '--'
            preq = Quotation.find_by(marketdate: pretradedate, code: q.code) 
            q.open = 0 
            q.high = 0 
            q.low = 0 
            q.close = cols[14].strip
					  q.dprofit = 0 

            q.tpstatus = 'tingpai' 
          else
            q.open = cols[11].strip
            q.high = cols[12].strip
            q.low = cols[13].strip
            q.close = cols[3].strip

					  q.dprofit = cols[2].strip
          end
					
          q.save
        end
      end
    end
	end	
		
	def updateReserves
		Reserve.where(marketdate: pretradedate, stockstatus: 1).each do |reserve|
			r = reserve.dup
			r.marketdate = tradedate
			
			r.quotation = Quotation.where(marketdate: tradedate, code:reserve.quotation.code).first
			
			unless r.hhv.nil? || r.quotation.nil? || r.hhv > r.quotation.close
				r.hhv = r.quotation.close 
				r.hdate = tradedate
				r.optadvise = 'sell'
				r.stockstatus = '2'
        r.releasedate = tradedate
			end
			unless r.llv.nil? || r.quotation.nil? || r.llv < r.quotation.close
				r.llv = r.quotation.close 
				r.ldate = tradedate
				r.optadvise = 'sell'
				r.stockstatus = '0'
        r.releasedate = tradedate
			end
			
			r.profit = (r.hhv - r.quotation.close)/r.quotation.close unless r.hhv.nil? || r.quotation.nil? || r.quotation.close.nil? || r.quotation.close == 0
			r.loss = (r.quotation.close - r.llv)/r.quotation.close unless r.llv.nil? || r.quotation.nil? || r.quotation.close.nil? || r.quotation.close == 0
			unless r.profit.nil? || r.loss.nil?
				if r.profit > 0 and r.loss > 0
					r.plratio = r.profit/r.loss
          r.winpercentage = 1/(1+r.plratio)
          if r.plratio > 2
            r.optadvise = 'buy'
            r.catchplratio = r.plratio
          elsif r.optadvise = 'buy'
            r.optadvise = '' 
          end
				else
					r.plratio = 0
				end
			end
			
			r.save!	unless r.quotation.nil?
		end
	end
		
	def updatePortfolios
		Portfolio.where(marketdate: pretradedate).each do |portfolio|
			next unless portfolio.sellprice.nil?

			p = portfolio.dup 

			p.marketdate = tradedate
			
			p.quotation = Quotation.where(marketdate: tradedate, code:portfolio.quotation.code).first
			
			case p.option 
			when 'buy' #execute buy option			
				p.buyprice = p.quotation.open
				p.buydate = tradedate
				p.profit = 0
				p.volum = 1 / sysportfolio_num_max
				p.option = 'hold'
			when 'hold'	
				#p.profit = (p.quotation.close - p.buyprice)/p.buyprice
				p.profit += p.quotation.dprofit
			when 'sell' #execute sell option
				#p.profit = (p.quotation.open - p.buyprice)/p.buyprice
				p.profit += p.quotation.dprofit
				p.sellprice = p.quotation.open
				p.selldate = tradedate
				if p.account.preprofit.nil? 
					p.account.preprofit = 0
				end
				p.account.preprofit += p.profit / sysportfolio_num_max
				if p.account.pretradenum.nil? 
					p.account.pretradenum = 0
				end
				p.account.pretradenum += 1
				if p.account.prewincount.nil? 
					p.account.prewincount = 0
				end
				if p.account.prelosscount.nil? 
					p.account.prelosscount = 0
				end
				if p.profit > 0
					p.account.prewincount += 1	
				else
					p.account.prelosscount += 1	
				end
				
			else
					
			end
			p.duration += 1 # duration init with 0
			
			p.account.save!			
			p.save!
		end
	end
	
	def updateAccounts
		Account.all.each do |account|	
		
			account.tradenum = account.pretradenum
			account.profit = account.preprofit
			account.wincount = account.prewincount
			account.losscount = account.prelosscount	

			Portfolio.where("account_id = ? and marketdate = ? and option = 'hold'", account.id, tradedate).each do |p|
				account.profit += p.profit/sysportfolio_num_max	
				account.tradenum += 1
				if p.profit > 0
					account.wincount += 1	
				else
					account.losscount += 1
				end
			end
			account.winratio = account.wincount/account.tradenum unless account.tradenum == 0 or account.wincount.nil? or account.wincount < 1 or account.losscount.nil? or account.losscount < 1
			if account.profitmax.nil?
				account.profitmax = 0
			end	
			if account.lossmax.nil?
				account.lossmax = 0
			end	
			account.profitmax = account.profit unless account.profitmax.nil? or account.profit.nil? or account.profitmax > account.profit
			account.lossmax = account.profit unless account.lossmax.nil? or account.profit.nil? or account.lossmax < account.profit
			account.plratio = account.profit/account.lossmax unless account.profitmax.nil? || account.lossmax.nil? || account.lossmax == 0
			if account.duration.nil?
				account.duration = 0
			end	
			account.duration += 1 #duration init with 0
			
			account.marketdate = tradedate
			
			account.save!
		end
	end

  def reservefileprocess path 
    File.open(path, 'r') do |file|
      file.each_line do |line|
        cols = line.force_encoding('gb2312').split("\t")
        if /\d{6}/ =~ cols[0][2..7].strip
          q = Quotation.find_or_initialize_by(code: cols[0][2..7].strip, marketdate: tradedate)
          q.marketdate = tradedate
 
          q.code = cols[0][2..7].strip
          q.name = cols[1].strip
					unless q.name.include? "ST"
            q.plate = cols[18].strip

            q.open = cols[11].strip
            q.high = cols[12].strip
            q.low = cols[13].strip
            q.close = cols[3].strip
            q.dprofit = cols[2].strip
            
            prer = Reserve.where(marketdate: tradedate, quotation_id: q.id).first
            #preq = Quotation.find_by(marketdate: pretradedate, code: q.code)
            odsr = Odsreserf.find_by(code: q.code)
           
            if odsr.nil? 
              Odsreserf.create!(code: q.code, name: q.name, plate: q.plate, open: q.open, high: q.high, low: q.low, close: q.close, dprofit: q.dprofit, duration: 1)
              if prer.nil?
                r = q.reserve.build(marketdate: tradedate, catchdate: tradedate, duration: 0, analyst_id: current_user.analyst.id )

                r.save!
              #else
              #	r = prer.dup
              #	q.reserve << r
              end
            else
              odsr.duration = 1
              odsr.save!
            end

            q.save!
					end
        end
      end
    end
	end	

  def odsreservefileprocess path 

    Odsreserf.delete_all

    File.open(path, 'r') do |file|
      file.each_line do |line|
        cols = line.force_encoding('gb2312').split("\t")
        if /\d{6}/ =~ cols[0][2..7].strip
					unless cols[1].strip.include? "ST"
           Odsreserf.create!(code: cols[0][2..7].strip, name: cols[1].strip, plate: cols[18].strip, open: cols[11].strip, high: cols[12].strip, low: cols[13].strip, close: cols[3].strip, dprofit: cols[2].strip, duration: 1)
          end
        end
      end
    end
	end	

	# data 	
	def doadvise
		#Reserve.daydata(sysmarketdate).where("optadvise == 'sell'").each do |r|
		Analyst.all.each do |analyst|
			analyst.reserve.daydata(sysmarketdate).each do |r|
			#analyst.reserve.daydata(sysmarketdate).where("optadvise == 'sell'").each do |r|
        r.duration += 1 unless r.stockstatus != '1'
        r.save!
        unless r.optadvise != 'sell'
          #Portfolio.daydata(tradedate).each do |p|
          analyst.accounts.each do |account|
            account.portfolios.daydata(tradedate).each do |p|
              if p.quotation.code == r.quotation.code
                p.option = r.optadvise 
                p.save!
              end
            end
          end
				end

app/views/quotationdatafiles/_form.html.erb
<%= simple_form_for @quotationdatafile, :html => { :class => 'form-horizontal', :multipart => true } do |f| %>
  <%= f.input :filetype %>
  <%= error_span(@quotationdatafile[:filetype]) %>
  <%= f.input :filestatus %>
  <%= error_span(@quotationdatafile[:filestatus]) %>
  <%= f.input :avatar_file_name %>
  <%= error_span(@quotationdatafile[:avatar_file_name]) %>
  <%= f.input :avatar_content_type %>
  <%= error_span(@quotationdatafile[:avatar_content_type]) %>
  <%= f.input :avatar_file_size %>
  <%= error_span(@quotationdatafile[:avatar_file_size]) %>
  <%= f.input :avatar_updated_at %>
  <%= error_span(@quotationdatafile[:avatar_updated_at]) %>
  <%= f.input :marketdate %>
  <%= error_span(@quotationdatafile[:marketdate]) %>
  <%= f.file_field :avatar %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                quotationdatafiles_path, :class => 'btn btn-default' %>
<% end %>

app/views/quotationdatafiles/edit.html.erb
<%- model_class = Quotationdatafile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quotationdatafiles/index.html.erb
<%- model_class = Quotationdatafile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:filetype) %></th>
      <th><%= model_class.human_attribute_name(:filestatus) %></th>
      <th><%= model_class.human_attribute_name(:avatar_file_name) %></th>
      <th><%= model_class.human_attribute_name(:avatar_content_type) %></th>
      <th><%= model_class.human_attribute_name(:avatar_file_size) %></th>
      <th><%= model_class.human_attribute_name(:avatar_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:marketdate) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @quotationdatafiles.each do |quotationdatafile| %>
      <tr>
        <td><%= link_to quotationdatafile.id, quotationdatafile_path(quotationdatafile) %></td>
        <td><%= quotationdatafile.filetype %></td>
        <td><%= quotationdatafile.filestatus %></td>
        <td><%= quotationdatafile.avatar_file_name %></td>
        <td><%= quotationdatafile.avatar_content_type %></td>
        <td><%= quotationdatafile.avatar_file_size %></td>
        <td><%= quotationdatafile.avatar_updated_at %></td>
        <td><%= quotationdatafile.marketdate %></td>
        <td><%=l quotationdatafile.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_quotationdatafile_path(quotationdatafile), :class => 'btn btn-default btn-xs' %>
           <%= if quotationdatafile.filetype == 'bxc'
                link_to t('.action', :default => t("helpers.links.action")),
                      bxctoodsupdate_quotationdatafile_path(quotationdatafile), :class => 'btn btn-default btn-xs'
                end
             %>
        
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      quotationdatafile_path(quotationdatafile),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_quotationdatafile_path,
            :class => 'btn btn-primary' %>

app/views/quotationdatafiles/new.html.erb
<%- model_class = Quotationdatafile -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/quotationdatafiles/show.html.erb
<%- model_class = Quotationdatafile -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:filetype) %>:</strong></dt>
  <dd><%= @quotationdatafile.filetype %></dd>
  <dt><strong><%= model_class.human_attribute_name(:filestatus) %>:</strong></dt>
  <dd><%= @quotationdatafile.filestatus %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @quotationdatafile.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @quotationdatafile.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @quotationdatafile.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @quotationdatafile.avatar_updated_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:marketdate) %>:</strong></dt>
  <dd><%= @quotationdatafile.marketdate %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              quotationdatafiles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_quotationdatafile_path(@quotationdatafile), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              quotationdatafile_path(@quotationdatafile),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>