config/routes.rb
Rails.application.routes.draw do
  resources :everydaytips

  resources :odsreserves

  get 'about/help'

  resources :analysts

  resources :syslogs

  resources :portfoliologs

  resources :weixinlogs

  resources :marketdates do
		get 'reset_marketdate_to_today', on: :collection
	end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { sessions: "users/sessions" }
  get 'welcome/index'

  resources :sysconfigs

  resources :quotationdatafiles do
		get 'doupdate', on: :member
		get 'bxctoodsupdate', on: :member
		get 'dobatch', on: :collection
	end

  resources :reserves do
    post 'qcode', on: :collection
    get 'pubindex', on: :collection
  end

  resources :quotations

  resources :accounts

  resources :portfolios

  resources :users

  mount WeixinRailsMiddleware::Engine, at: "/"

  get '/pub/index', to: 'reserves#pubindex', as: 'sysanalyst'
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
		if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/account.rb
class Account < ActiveRecord::Base
	has_attached_file :avatar, 
	:styles => { 
		:medium => {
			:processors =>[:watermark], 
			:geometry => '800x500',
			:watermark_path => "#{Rails.root}/public/1.jpg",
			:percentage => '20%',
			:position => 'Center'
		}
	}, 
	:path => ":rails_root/public/downloads/:id.:extension",
	:url => "/downloads/:id.:extension",
	:default_url => "/downloads/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
	has_many	:portfolios
	#has_many	:follows
	#has_many	:analysts, through: :follows
	belongs_to :analyst
	belongs_to	:user
	resourcify
end

app/models/analyst.rb
class Analyst < ActiveRecord::Base
	has_many	:reserve
	#has_many	:follows
	#has_many	:accounts, through: :follows
	has_many	:accounts
  belongs_to :user
end

app/models/everydaytip.rb
class Everydaytip < ActiveRecord::Base
end

app/models/marketdate.rb
class Marketdate < ActiveRecord::Base
end

app/models/odsreserf.rb
class Odsreserf < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
	belongs_to	:account
	belongs_to	:quotation
	resourcify
	scope :daydata, ->(marketdate) { where("marketdate = ?", marketdate) }
end

app/models/portfoliolog.rb
class Portfoliolog < ActiveRecord::Base
end

app/models/quotation.rb
class Quotation < ActiveRecord::Base
	resourcify
	scope :daydata, ->(marketdate) { where("marketdate = ?", marketdate) }
	has_many	:portfolio
	has_many	:reserve
end

app/models/reserve.rb
class Reserve < ActiveRecord::Base
	include QuotationdatafilesHelper
	belongs_to	:quotation
	belongs_to	:analyst
	resourcify
	scope	:daydata, ->(marketdate) { where("marketdate = ?", marketdate) }
	
	class << self
		def refresh(close)
			unless close <= 0
         profit = (hhv - close)/close
         loss = (close - llv)/close
         plratio = profit / loss
         optadvise = 'buy' unless plratio < 2
         stockstatus = 1
       end
		end
	end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/sysconfig.rb
class Sysconfig < ActiveRecord::Base
  has_attached_file :imgfile, 
      :styles => { :poster => "1280x1280", :large => "860x860", :medium => "430x430", :small => "344x344", :thumb => "258x258" }

      validates_attachment :imgfile,
      :content_type => { :content_type => /\Aimage\/.*\Z/ } ,
      :size => { :in => 0..1000.kilobytes }


  has_attached_file :txtfile 

      validates_attachment :txtfile,
      :content_type => { :content_type => ["text/plain"] } ,
      :size => { :in => 0..1000.kilobytes }

	resourcify
end

app/models/syslog.rb
class Syslog < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable
	has_many	:accounts
  has_one :analyst
end

app/models/weixinlog.rb
class Weixinlog < ActiveRecord::Base
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	before_filter :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:setdate,:marketdate, :name, :profit, :tradenum, :winratio, :plratio, :profitmax, :lossmax, :duration, :avatar)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/analysts_helper.rb
module AnalystsHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
	def reserve_update_hhv_llv(reserve)
    unless reserve.quotation.nil? || reserve.hhv.nil? || reserve.llv.nil? || reserve.quotation.close <= 0
   	  reserve.profit = (reserve.hhv - reserve.quotation.close)/reserve.quotation.close
      reserve.loss = (reserve.quotation.close - reserve.llv)/reserve.quotation.close
      reserve.plratio = reserve.profit / reserve.loss unless reserve.loss == 0
      reserve.winpercentage = 1/(1+reserve.plratio)
			if reserve.plratio >= 2
				reserve.optadvise = 'buy'
        reserve.catchplratio = reserve.plratio
			else 
				if reserve.optadvise == 'buy'
      		reserve.optadvise = ''
				end
			end
      reserve.stockstatus = 1
      reserve.save
    end
  end
end

app/helpers/syslogs_helper.rb
module SyslogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for @account, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :setdate %>
  <%= error_span(@account[:setdate]) %>
  <%= f.input :name %>
  <%= error_span(@account[:name]) %>
  <%= f.input :tradenum %>
  <%= error_span(@account[:tradenum]) %>
  <%= f.input :winratio %>
  <%= error_span(@account[:winratio]) %>
  <%= f.input :plratio %>
  <%= error_span(@account[:plratio]) %>
  <%= f.input :profitmax %>
  <%= error_span(@account[:profitmax]) %>
  <%= f.input :lossmax %>
  <%= error_span(@account[:lossmax]) %>
  <%= f.input :user_id %>
  <%= error_span(@account[:user_id]) %>
  <%= f.input :marketdate %>
  <%= error_span(@account[:marketdate]) %>
  <%= f.input :duration %>
  <%= error_span(@account[:duration]) %>
  <%= f.input :wincount %>
  <%= error_span(@account[:wincount]) %>
  <%= f.input :losscount %>
  <%= error_span(@account[:losscount]) %>
  <%= f.input :profit %>
  <%= error_span(@account[:profit]) %>
  <%= f.input :pretradenum %>
  <%= error_span(@account[:pretradenum]) %>
  <%= f.input :preprofit %>
  <%= error_span(@account[:preprofit]) %>
  <%= f.input :prewincount %>
  <%= error_span(@account[:prewincount]) %>
  <%= f.input :prelosscount %>
  <%= error_span(@account[:prelosscount]) %>
  <%= f.input :avatar_file_name %>
  <%= error_span(@account[:avatar_file_name]) %>
  <%= f.input :avatar_content_type %>
  <%= error_span(@account[:avatar_content_type]) %>
  <%= f.input :avatar_file_size %>
  <%= error_span(@account[:avatar_file_size]) %>
  <%= f.input :avatar_updated_at %>
  <%= error_span(@account[:avatar_updated_at]) %>
  <%= f.input :analyst_id %>
  <%= error_span(@account[:analyst_id]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                accounts_path, :class => 'btn btn-default' %>
<% end %>

app/views/accounts/edit.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:setdate) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:tradenum) %></th>
      <th><%= model_class.human_attribute_name(:winratio) %></th>
      <th><%= model_class.human_attribute_name(:plratio) %></th>
      <th><%= model_class.human_attribute_name(:profitmax) %></th>
      <th><%= model_class.human_attribute_name(:lossmax) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:marketdate) %></th>
      <th><%= model_class.human_attribute_name(:duration) %></th>
      <th><%= model_class.human_attribute_name(:wincount) %></th>
      <th><%= model_class.human_attribute_name(:losscount) %></th>
      <th><%= model_class.human_attribute_name(:profit) %></th>
      <th><%= model_class.human_attribute_name(:pretradenum) %></th>
      <th><%= model_class.human_attribute_name(:preprofit) %></th>
      <th><%= model_class.human_attribute_name(:prewincount) %></th>
      <th><%= model_class.human_attribute_name(:prelosscount) %></th>
      <th><%= model_class.human_attribute_name(:avatar_file_name) %></th>
      <th><%= model_class.human_attribute_name(:avatar_content_type) %></th>
      <th><%= model_class.human_attribute_name(:avatar_file_size) %></th>
      <th><%= model_class.human_attribute_name(:avatar_updated_at) %></th>
      <th><%= model_class.human_attribute_name(:analyst_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.id, account_path(account) %></td>
        <td><%= account.setdate %></td>
        <td><%= account.name %></td>
        <td><%= account.tradenum %></td>
        <td><%= account.winratio %></td>
        <td><%= account.plratio %></td>
        <td><%= account.profitmax %></td>
        <td><%= account.lossmax %></td>
        <td><%= account.user_id %></td>
        <td><%= account.marketdate %></td>
        <td><%= account.duration %></td>
        <td><%= account.wincount %></td>
        <td><%= account.losscount %></td>
        <td><%= account.profit %></td>
        <td><%= account.pretradenum %></td>
        <td><%= account.preprofit %></td>
        <td><%= account.prewincount %></td>
        <td><%= account.prelosscount %></td>
        <td><%= account.avatar_file_name %></td>
        <td><%= account.avatar_content_type %></td>
        <td><%= account.avatar_file_size %></td>
        <td><%= account.avatar_updated_at %></td>
        <td><%= account.analyst_id %></td>
        <td><%=l account.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_account_path(account), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      account_path(account),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_account_path,
            :class => 'btn btn-primary' %>

app/views/accounts/new.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/accounts/show.html.erb
<%- model_class = Account -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:setdate) %>:</strong></dt>
  <dd><%= @account.setdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @account.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tradenum) %>:</strong></dt>
  <dd><%= @account.tradenum %></dd>
  <dt><strong><%= model_class.human_attribute_name(:winratio) %>:</strong></dt>
  <dd><%= @account.winratio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:plratio) %>:</strong></dt>
  <dd><%= @account.plratio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:profitmax) %>:</strong></dt>
  <dd><%= @account.profitmax %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lossmax) %>:</strong></dt>
  <dd><%= @account.lossmax %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @account.user_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:marketdate) %>:</strong></dt>
  <dd><%= @account.marketdate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:duration) %>:</strong></dt>
  <dd><%= @account.duration %></dd>
  <dt><strong><%= model_class.human_attribute_name(:wincount) %>:</strong></dt>
  <dd><%= @account.wincount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:losscount) %>:</strong></dt>
  <dd><%= @account.losscount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:profit) %>:</strong></dt>
  <dd><%= @account.profit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:pretradenum) %>:</strong></dt>
  <dd><%= @account.pretradenum %></dd>
  <dt><strong><%= model_class.human_attribute_name(:preprofit) %>:</strong></dt>
  <dd><%= @account.preprofit %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prewincount) %>:</strong></dt>
  <dd><%= @account.prewincount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prelosscount) %>:</strong></dt>
  <dd><%= @account.prelosscount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_name) %>:</strong></dt>
  <dd><%= @account.avatar_file_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_content_type) %>:</strong></dt>
  <dd><%= @account.avatar_content_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_file_size) %>:</strong></dt>
  <dd><%= @account.avatar_file_size %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar_updated_at) %>:</strong></dt>
  <dd><%= @account.avatar_updated_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:analyst_id) %>:</strong></dt>
  <dd><%= @account.analyst_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              accounts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_account_path(@account), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              account_path(@account),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>